# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Copy the requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application
COPY . .

# Expose the port Streamlit runs on
EXPOSE 8080

# Command to run the script
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8080"]